---
abstract: 'MIME::Base32::XS - Encoding and decoding Base32'
author:
  - 'Lucas Tiago de Moraes <lucastiagodemoraes@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MIME-Base32-XS
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: '0'
  XSLoader: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/lucas1/MIME-Base32-XS/issues
  homepage: https://github.com/lucas1/MIME-Base32-XS
  repository: https://github.com/lucas1/MIME-Base32-XS
version: '0.09'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
